server:
  port: 8082
user: 
  userServerPath: http://localhost:8081/hello/
spring: 
  application:
    name: microservice-consumer-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}